### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by abbychau** [entvex/NgrokGUI#1]
- store port and protocol records
- publish generated URL by a restful call
- auto start on windows start

**Comment by entvex** [comment]
Dear @abbychau. Thanks for the feature requests!

I just have some questions, to make sure i understand the requests right.

> - store port and protocol records

Are you using looking for this feature to reuse an a set of a previous created url? Because as far as i am know only the paid version of ngrok, allows that :). Or do you simply want the tunnels that are stopped, to stay in the tunnel list ?

> - publish generated URL by a restful call

Is this so when you created a new tunnel, that it has an option to send the url, as a rest call to another progream? I would love a little more details here

> - auto start on windows start

Would you just like the program to auto start the gui on start up ?

Also are you using the paid version of Ngrok?

I hope it makes sense, if not feel free to ask again :)

**Comment by abbychau** [comment]
> Are you using looking for this feature to reuse an a set of a previous created url? Because as far as i am know only the paid version of ngrok, allows that :). 
No.
> Or do you simply want the tunnels that are stopped, to stay in the tunnel list ?
just to store the protocol and port configs

> Is this so when you created a new tunnel, that it has an option to send the url, as a rest call to another progream? I would love a little more details here

actually any kind of triggering could work. other integrations can be done by simple scripting. but giving out the generated URL to a internet https endpoint makes most sense to me.

 > Would you just like the program to just auto start the gui on start up ?
 start and load the config so to generate URL automatically. that is bascially what people doing in the CLI version.
 
paid version and non-paid version just affect if the generated URL able to be static or not. it does not affect the functions above.

**Comment by entvex** [comment]
Dear @abbychau. Thanks for responding!

> > Are you using looking for this feature to reuse an a set of a previous created url? Because as far as i am know only the paid version of ngrok, allows that :).
> 
> No.
> 
> > Or do you simply want the tunnels that are stopped, to stay in the tunnel list ?
> 
> just to store the protocol and port configs

Ah!, I think I am starting to understand what you would like here :) . So when you go into the "new tunnel" and fills the information, you would like a way to save the details, so is easier to create the tunnel again, with previously entered data?

> > Is this so when you created a new tunnel, that it has an option to send the url, as a rest call to another progream? I would love a little more details here
> 
> actually any kind of triggering could work. other integrations can be done by simple scripting. but giving out the generated URL to a internet https endpoint makes most sense to me.

Yeah, okay, so after a tunnel have been created it should be able to do a http post, to a url, so a external program are able to use the tunnel.

> > start and load the config so to generate URL automatically. that is bascially what people doing in the CLI version.
> 
> paid version and non-paid version just affect if the generated URL able to be static or not. it does not affect the functions above.

Yeah, now I understand. So you would like NgrokGUI, to be able start with windows and create the tunnels specified in the Ngrok configuration file?

On another note, may I ask you how important, this application being cross platform is to you as a user of NgrokGUI

I hope it makes sense, if not feel free to ask again :). I will soon create tasks for these feature requests, when I am sure I understand your wishes.

**Comment by abbychau** [comment]
>so is easier to create the tunnel again, with previously entered data?
exactly. saving them into a json is quite important to make this more useful to me.

I think making it cross-platform is good; making the gui optional and add a cli mode that can read the same json and initiate the url triggers. this is a sensible enhancement in my opinion.

**Comment by entvex** [comment]
Dear @abbychau 
If you know, how to do it, you can take a look at the branch AllowUserToCreateTunnelWithSubDomain and compile the program. It should now, be easier recreate tunnels with previously entered data. #4. I still need to work on it a bit more, before i make a new release.

Also because I made #4 #5 and #6 based on your feedback, can i close this issue ? or do you have anymore feedback in here you feel I am missing.

**Comment by abbychau** [comment]
Thank you for the good works.
I seldom use windows recently. So I may get back to you later. Please feel free to close them if they are finished. I will check back later :)
